export const AREA_OPTIONS = [
  "Alt Camp",
  "Alt Empordà",
  "Alt Penedès",
  "Alt Urgell",
  "Alta Ribagorça",
  "Anoia",
  "Bages",
  "Baix Camp",
  "Baix Ebre",
  "Baix Empordà",
  "Baix Llobregat",
  "Barcelonès",
  "Berguedà",
  "Cerdanya",
  "Conca de Barberà",
  "Garraf",
  "Garrigues",
  "Garrotxa",
  "Gironès",
  "Maresme",
  "Moianès",
  "Montsià",
  "Noguera",
  "Osona",
  "Pallars Jussà",
  "Pallars Sobirà",
  "Pla d'Urgell",
  "Pla de l'Estany",
  "Priorat",
  "Ribera d'Ebre",
  "Ripollès",
  "Segarra",
  "Segrià",
  "Selva",
  "Solsonès",
  "Tarragonès",
  "Terra Alta",
  "Urgell",
  "Vallès Occidental",
  "Vallès Oriental",
  "Val d'Aran"
];

export const CLIENTS_OPTIONS = [
  "Alsa",
  "Avanza",
  "Monbus",
  "Hife",
  "FlixBus",
  "Socibus",
  "Damas",
  "Samar",
  "Moventis",
  "Sagalés",
  "TMB"
]

export const BCN_COORDS = {
  lat: 41.390205,
  lng: 2.154007
}
